apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: indico-postgres
    name: indico-postgres
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: indico-postgres
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: indico-postgres
    name: indico-postgres
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: centos/postgresql-94-centos7
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: indico-postgres
    name: indico-postgres
  spec:
    replicas: 1
    selector:
      io.kompose.service: indico-postgres
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: indico-postgres
      spec:
        containers:
        - env:
          - name: POSTGRESQL_USER
            value: indico
          - name: POSTGRESQL_PASSWORD
            value: indicopass
          - name: POSTGRESQL_DATABASE
            value: indico
          - name: POSTGRESQL_ADMIN_PASSWORD
            value: indicopass
          image: ' '
          name: indico-postgres
          resources: {}
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - indico-postgres
        from:
          kind: ImageStreamTag
          name: indico-postgres:latest
      type: ImageChange
  status: {}

